### ISSUE TITLE
Registration is stuck in the email validation step

### ISSUE THREAD

**Issue by LaurentVoillot** [dinsic-pim/tchap-ios#117]
When you create a account on a iPhone, the confirmation email launch : 
 - safari and not Tchap
 - and on Tchap the wheel continue without end

**Comment by giomfo** [comment]
- The first point requires to support universal links (https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html). A apple-app-site-association file will be uploaded soon to the web server.

- The second point is a bug

**Comment by giomfo** [comment]
The second point is fixed, the first one will be handled by #119
