### ISSUE TITLE
Tchap is stuck on the room preview whereas I joined with success the room 

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-ios#337]
To reproduce
- Create a private room
- Turn on the access by link
- Share the link to another agent user
- Click on the link with the other user account
- The preview is displayed OK
- Join the room -> a loading wheel is displayed -> the room display is not refresh, we are stuck on the preview NOK

Note If we return to the rooms lists, the room is displayed as joined, and we are able to select it and read its history (the join succeeded)

**Comment by yostyle** [comment]
I cannot reproduce it on iPhone 11 simulator with iOS 13.7

**Comment by yostyle** [comment]
I can reproduce it on iPhone 8 simulator with iOS 12.4
