### ISSUE TITLE
Add a shortcut "forward" in the selected message options

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-ios#353]
Presently to forward a message the Tchap-iOS user has to select the option share and select the Tchap application.

DINUM request to add a dedicated option "Transférer"  to prompt directly the room lists

**Comment by gileluard** [comment]
We can reuse `ShareViewController`, `SegmentedViewController`, `RoomsListViewController`, and `FallbackViewController` but we have to handle the `ShareExtensionManager` which is specialised for the Share Extension. The `ShareExtensionManager` is used to:
- get the user account
- access the file store
- receive event when account data is updated
- terminate the share extension
- send the content to a specific room

The `ShareDataSource`, used to populate the rooms list and the people's list, needs to be also updated

 3 possible strategies:
- We find a way to have a `GenericManager` (`ShareExtensionManager` will extend this `GenericManager `) and have another `GenericManager` for the app
- We can move the `ShareExtensionManager` to the `SharePresentingViewController`. This way, we can decouple all the data part from the Viewcontrollers
- We can rewrite `ShareViewController`, `SegmentedViewController`, `RoomsListViewController`, and `FallbackViewController` which are not that big

**Comment by giomfo** [comment]
I would prefer to go for the third strategy, I mean create a new "ShareViewController" named "TransferViewController " (as you said)
I would not consider a segmented view controller. I suggest displaying the rooms list by using the existing `RoomsViewController`, a search bar is required at the top of the list.
I would use the delegate method "- (void)roomsViewController:(RoomsViewController*)roomsViewController didSelectRoomWithID:(NSString*)roomID;" to handle the selection and send the selected content
