### ISSUE TITLE
Add the option to import the encryption keys in the Tchap settings

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-ios#360]
Currently the user is allowed to export the keys from the settings screen,
We have to add the option to import a file from the file system

**Comment by giomfo** [comment]
The request here is:
- add the option "Importer des clés" just below the existing "Exporter les clés" in the Settings screen
- open the file explorer (like we do currently to attach a file into a room), check whether the file is a keys file (like we do on attached file), and prompt the user to import or not by considering the following popup:
![image](https://user-images.githubusercontent.com/8969772/105728144-1aeef600-5f2c-11eb-9d02-01f8c7e75b56.png)

**Comment by gileluard** [comment]
Just need 1 hour or 2.
