### ISSUE TITLE
[Room retention] Support unlimited room history

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-ios#361]
After thinking, we decided to let the admin decide about the room history between a predefined values:
- 1 day
- 1 week
- 1 month
- 1 year
- no limit

This set of values must be confirmed by the DINUM

On client, we have to update the existing UI, and consider "no limit" by default instead of "1 year"

**Comment by giomfo** [comment]
The actions on this point for Tchap-iOS are:
- [ ] Room creation: remove the existing code related to the room retention. We don't want to handle this parameter on room creation for the moment.
- [ ] Remove `DEFAULT_RETENTION_VALUE_IN_DAYS` from the code, we don't want anymore a default value. The actual default is null (= unlimited)
- [ ] MXRoomSummary: 
   - the value returned by [tc_roomRetentionPeriodInDays](https://github.com/dinsic-pim/tchap-ios/blob/develop/Tchap/Extensions/MXRoomSummary.swift#L127) becomes nullable -> `func tc_roomRetentionPeriodInDays() -> uint? " 
   - [tc_removeExpiredRoomContentsFromStore](https://github.com/dinsic-pim/tchap-ios/blob/develop/Tchap/Extensions/MXRoomSummary.swift#L147) must do nothing and return false if `tc_roomRetentionPeriodInDays()` returns null for the concerned room.
   - Force [here](https://github.com/dinsic-pim/tchap-ios/blob/develop/Tchap/Modules/Application/AppCoordinator.swift#L26) a clear cache on the next update after the change of the 2 previous functions.
- [ ] Room settings:
   - rename the parameter with "Durée de l'historique"
   - the values are predefined, they are suggested into a picker (the higher value at the top): "illimitée", "1 an", "6 mois", "1 mois", "1 semaine", "1 jour".
   - As soon as a value doesn't match with one of the predefined values, we use a count of days (jours)
   - I think we will need a function to compare/convert a days count into the predefined value. I would add it into the Tools class. 
- [ ] Room History: display a message into the room history for each "m.room.retention" event : "Arthur Martin [Modernisation] a limité l'historique à 1 mois"
- [ ] Room title: 
   - Change the existing code to keep the room title on 2 lines.
   - Change the label "Salon privé ouvert aux externes" with "Ouvert aux externes"
   - Do not mention the retention period when the history is unlimited (illimitée)
   - Add at the end of the second lines the current retention period (see the design which will be added soon)

**Comment by giomfo** [comment]
@yostyle Until the design is provided, please work only on the 2 first points
after thinking a default value -1 seems better than the null value, I let you decide

**Comment by yostyle** [comment]
> * the value returned by [tc_roomRetentionPeriodInDays](https://github.com/dinsic-pim/tchap-ios/blob/develop/Tchap/Extensions/MXRoomSummary.swift#L127) becomes nullable -> `func tc_roomRetentionPeriodInDays() -> uint? "

I can't do this because return an optional value is not permit on objc.

**Comment by giomfo** [comment]
I blocked this issue until PR #367 is merged and I add the design request for the next points

**Comment by giomfo** [comment]
The design of the room header is:
![image](https://user-images.githubusercontent.com/8969772/111550814-38e41480-877f-11eb-9923-a292395bb3e8.png)

the retention information is displayed only if the value is not unlimited.
An icon is added on each information (type, members, retention)

In the room settings, the room retention is handled thanks to a picker with a limited values:
![image](https://user-images.githubusercontent.com/8969772/111551030-98422480-877f-11eb-9c63-591909e081e3.png)
