### ISSUE TITLE
Antivirus - Media scan: Implement the MediaScanManager

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-ios#77]
Add a new module "MXMediaScanManager" in the matrix-ios-sdk used to scan a media url.

This manager should:
- return the current scan result of an unencrypted, or encrypted media (by considering its url). 
- trigger an antivirus scan if it is not already done.
- use Realm to store scan status of the media
A first implementation of this manager is available in Tchap-Android: https://github.com/dinsic-pim/tchap-android/tree/develop/vector/src/main/java/fr/gouv/tchap/media.

We have to define a new object used to store scan result including the antivirus status. Let name it `MXMediaScan` (see https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/model/MediaScan.java).

The client-server API is described here:
- for [unencrypted media](https://github.com/matrix-org/matrix-content-scanner/blob/master/README.md#get-scandomainmediaid): 
- for [encrypted media ](https://github.com/matrix-org/matrix-content-scanner/blob/master/README.md#post-scan_encrypted)
An implementation is available in matrix-android-sdk: https://github.com/matrix-org/matrix-android-sdk/blob/521dd15efbbdf95e1ab70ed5a33e95656b2fa0ad/matrix-sdk/src/main/java/org/matrix/androidsdk/rest/client/MediaScanRestClient.java

**Comment by LaurentVoillot** [comment]
Not Yet done, my iphone My iphone loop on antivirus scan and after "analyse indisponible"

**Comment by giomfo** [comment]
@LaurentVoillot FYI I reproduced your issue. I filed an issue on server side: https://github.com/matrix-org/matrix-dinsic/issues/149
